site_name: Systems & Graphics Notes
nav:
        - Home: index.md
        - Colors: colordepth.md
        - Line: linealgorithm.md
        - Matrix: matrix.md
        - Transformations: transformations.md
        - Parametric: parametric.md
        - Splines: splines.md
        - 3D Shapes: 3dshapes.md
theme: readthedocs
