/usr/bin/setxkbmap -option "caps:swapescape"
alias l='ls -l'
alias python='python3'
alias pip='pip3'
alias nvim='vim'
alias rusty='. ~/.venv/rusty/bin/activate'
alias sd='cd ~/wahksphass/stuy-cs/softdev'
alias sys='cd ~/wahksphass/stuy-cs/systems'
alias rmr='~/.shellscript/remove_chmod.sh'
alias gcc='~/.shellscript/gcc_and_run.sh'

